---
- name: Install jq 
  package:
    name: jq 
    state: present 

- name: Get terraform latest version
  shell: curl {{ tf_api_url }} | jq -r .current_version
  args:
    warn: False 
  changed_when: False 
  register: tf_version

- name: Override tf_version in defaults
  set_fact:
    tf_version: "{{ tf_version['stdout'] }}"

- name: Grab terraform latest binary 
  unarchive: 
    src: "{{ tf_url }}"
    dest: /usr/bin/
    remote_src: true
  become: true